version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT_ALLOW_PLAYGROUND=true
    networks:
      - app_network
    healthcheck:
      disable: true

volumes:
  qdrant_data:
    driver: local

networks:
  app_network:
    driver: bridge
