name: Code Quality

on:
  push:
    branches: [main]
    paths-ignore:
      - 'research/**'
  pull_request:
    branches: [main]
    paths-ignore:
      - 'research/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install UV
        run: pip install uv

      - name: Install dependencies
        run: |
          uv venv
          source .venv/bin/activate
          uv pip install -e ".[dev]"

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0 